### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by Jaecen** [Jaecen/Peregrine#26]
Users need to be able to authenticate with the service. Authentication will be used to define roles, restrict visibility, and allow admin access.

We will support third-party logins (Google, Facebook, etc.).

For dev purposes, we will support username/password logins.

**Comment by friendscottn** [comment]
- I added authorize attributes to the api controllers that needed it. Seems to work pretty well controlling access this way.
- I added Google to the external login page. The button link does not work for some reason. I'm going to move onto Facebook to see if it has the same problem.

**Comment by friendscottn** [comment]
I've been working steady on this for a full year and a half. I'm happy to report I sorted it out.
